###############################################################################
# Codex Configuration
#
# DESCRIPTION
#   Configuration file for Codex, OpenAI's agentic coding assistant.
#
#   See: https://github.com/openai/codex
#
# INSTALLATION
#   Symlink file to $HOME/.codex/config.toml:
#
#     ln -s .codex/config.toml $HOME/.codex/config.toml
###############################################################################

model = "gpt-5.4"
approval_mode = "auto-edit"
model_reasoning_effort = "xhigh"

[notice]
  hide_gpt5_1_migration_prompt = true
  "hide_gpt-5.1-codex-max_migration_prompt" = true

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"

[features]
  apps = true
  multi_agent = true
  shell_snapshot = true
  unified_exec = true

[projects."/"]
  trust_level = "trusted"

[projects."/Users/nickolas"]
  trust_level = "trusted"

[projects."/Users/nickolas/nickolashkraus"]
  trust_level = "trusted"

[projects."/Users/nickolas/nickolashkraus/terminal"]
  trust_level = "trusted"

[projects."/Users/nickolas/grind-rip"]
  trust_level = "trusted"

[projects."/Users/nickolas/Function-Health/auth0-acul"]
  trust_level = "trusted"

[projects."/Users/nickolas/nickolashkraus/dotfiles"]
  trust_level = "trusted"

[projects."/Users/nickolas/nickolashkraus/agent-os"]
  trust_level = "trusted"

[tui]
  theme = "base16"
