apiVersion: v1
kind: Config
preferences: {}

clusters:
###############################################################################
# Granular Lite - Dev
#
# Comprises the following Kubernetes clusters:
#   * Granular Lite - Dev - BR - Kubernetes
#   * Granular Lite - Dev - CA - Kubernetes
#   * Granular Lite - Dev - US - Kubernetes
###############################################################################
  - cluster:
      certificate-authority: ./certs/cluster.br.dev.lite.granular.ag/k8s-ca.crt
      server: https://api.cluster.br.dev.lite.granular.ag
    name: cluster.br.dev.lite.granular.ag
  - cluster:
      certificate-authority: ./certs/cluster.ca.dev.lite.granular.ag/k8s-ca.crt
      server: https://api.cluster.ca.dev.lite.granular.ag
    name: cluster.ca.dev.lite.granular.ag
  - cluster:
      certificate-authority: ./certs/cluster.us.dev.lite.granular.ag/k8s-ca.crt
      server: https://api.cluster.us.dev.lite.granular.ag
    name: cluster.us.dev.lite.granular.ag
###############################################################################
# Granular Lite - Test
#
# Comprises the following Kubernetes clusters:
#   * Granular Lite - Test - BR - Kubernetes
#   * Granular Lite - Test - CA - Kubernetes
#   * Granular Lite - Test - US - Kubernetes
###############################################################################
  - cluster:
      certificate-authority: ./certs/cluster.br.test.lite.granular.ag/k8s-ca.crt
      server: https://api.cluster.br.test.lite.granular.ag
    name: cluster.br.test.lite.granular.ag
  - cluster:
      certificate-authority: ./certs/cluster.ca.test.lite.granular.ag/k8s-ca.crt
      server: https://api.cluster.ca.test.lite.granular.ag
    name: cluster.ca.test.lite.granular.ag
  - cluster:
      certificate-authority: ./certs/cluster.us.test.lite.granular.ag/k8s-ca.crt
      server: https://api.cluster.us.test.lite.granular.ag
    name: cluster.us.test.lite.granular.ag
###############################################################################
# Granular Lite - Production
#
# Comprises the following Kubernetes clusters:
#   * Granular Lite - Test - AU - Kubernetes
#   * Granular Lite - Test - BR - Kubernetes
#   * Granular Lite - Test - CA - Kubernetes
#   * Granular Lite - Test - US - Kubernetes
###############################################################################
  - cluster:
      certificate-authority: ./certs/cluster.au.lite.granular.ag/k8s-ca.crt
      server: https://api.cluster.au.lite.granular.ag
    name: cluster.au.lite.granular.ag
  - cluster:
      certificate-authority: ./certs/cluster.br.lite.granular.ag/k8s-ca.crt
      server: https://api.cluster.br.lite.granular.ag
    name: cluster.br.lite.granular.ag
  - cluster:
      certificate-authority: ./certs/cluster.ca.lite.granular.ag/k8s-ca.crt
      server: https://api.cluster.ca.lite.granular.ag
    name: cluster.ca.lite.granular.ag
  - cluster:
      certificate-authority: ./certs/cluster.us.lite.granular.ag/k8s-ca.crt
      server: https://api.cluster.us.lite.granular.ag
    name: cluster.us.lite.granular.ag
###############################################################################
# encshared*
#
# Comprises the following Kubernetes clusters:
#   * encsharedtest
#   * encsharedprod
###############################################################################
  - cluster:
      certificate-authority: ./certs/cluster.prod.shared.encirca.pioneer.com/k8s-ca.crt
      server: https://api.cluster.prod.shared.encirca.pioneer.com
    name: cluster.prod.shared.encirca.pioneer.com
  - cluster:
      certificate-authority: ./certs/cluster.test.shared.encirca.pioneer.com/k8s-ca.crt
      server: https://api.cluster.test.shared.encirca.pioneer.com
    name: cluster.test.shared.encirca.pioneer.com
###############################################################################
# ensharedtest
#
# Comprises the following Kubernetes clusters:
#   * encsharedtest - Dev Ops Development Cluster
###############################################################################
  - cluster:
      certificate-authority: ./certs/cluster2.test.shared.encirca.pioneer.com/k8s-ca.crt
      server: https://api.cluster2.test.shared.encirca.pioneer.com
    name: cluster2.test.shared.encirca.pioneer.com

contexts:
###############################################################################
# Granular Lite - Dev
###############################################################################
  - context:
      cluster: cluster.br.dev.lite.granular.ag
      user: nickolaskraus-cluster.br.dev.lite.granular.ag
    name: cluster.br.dev.lite.granular.ag
  - context:
      cluster: cluster.ca.dev.lite.granular.ag
      user: nickolaskraus-cluster.ca.dev.lite.granular.ag
    name: cluster.ca.dev.lite.granular.ag
  - context:
      cluster: cluster.us.dev.lite.granular.ag
      user: nickolaskraus-cluster.us.dev.lite.granular.ag
    name: cluster.us.dev.lite.granular.ag
###############################################################################
# Granular Lite - Test
###############################################################################
  - context:
      cluster: cluster.br.test.lite.granular.ag
      user: nickolaskraus-cluster.br.test.lite.granular.ag
    name: cluster.br.test.lite.granular.ag
  - context:
      cluster: cluster.ca.test.lite.granular.ag
      user: nickolaskraus-cluster.ca.test.lite.granular.ag
    name: cluster.ca.test.lite.granular.ag
  - context:
      cluster: cluster.us.test.lite.granular.ag
      user: nickolaskraus-cluster.us.test.lite.granular.ag
    name: cluster.us.test.lite.granular.ag
###############################################################################
# Granular Lite - Production
###############################################################################
  - context:
      cluster: cluster.au.lite.granular.ag
      user: nickolaskraus-cluster.au.lite.granular.ag
    name: cluster.au.lite.granular.ag
  - context:
      cluster: cluster.br.lite.granular.ag
      user: nickolaskraus-cluster.br.lite.granular.ag
    name: cluster.br.lite.granular.ag
  - context:
      cluster: cluster.ca.lite.granular.ag
      user: nickolaskraus-cluster.ca.lite.granular.ag
    name: cluster.ca.lite.granular.ag
  - context:
      cluster: cluster.us.lite.granular.ag
      user: nickolaskraus-cluster.us.lite.granular.ag
    name: cluster.us.lite.granular.ag
###############################################################################
# encshared*
###############################################################################
  - context:
      cluster: cluster.prod.shared.encirca.pioneer.com
      user: nickolaskraus-cluster.prod.shared.encirca.pioneer.com
    name: cluster.prod.shared.encirca.pioneer.com
  - context:
      cluster: cluster.test.shared.encirca.pioneer.com
      user: nickolaskraus-cluster.test.shared.encirca.pioneer.com
    name: cluster.test.shared.encirca.pioneer.com
###############################################################################
# ensharedtest
###############################################################################
  - context:
      cluster: cluster2.test.shared.encirca.pioneer.com
      user: nickolaskraus-cluster2.test.shared.encirca.pioneer.com
    name: cluster2.test.shared.encirca.pioneer.com

users: []
