#!/usr/bin/env python3
"""Single source of truth for the AI-slop catalogue from rules/general.md.

`lint-outbound.py` imports `AI_SLOP_PATTERNS` from here for its deterministic
pass. The prose bullets under "do not speak like an LLM" in rules/general.md
are generated from the same entries by `--sync-rules`, so a word cannot exist
in one place and be missing from the other.

Adding a tic:

    1. Add or edit an `Entry` below.
    2. Run `python3 ai_slop.py --sync-rules`.
    3. Commit both files.

`--check-rules` re-renders and diffs without writing; it exits 1 when
rules/general.md has drifted.

An entry with `pattern=None` is one only the LLM pass in `rule-check.py` can
see (a structural shape rather than a fixed phrase). It appears in the rules
file and is skipped by the regex pass.
"""

from __future__ import annotations

import argparse
import dataclasses
import difflib
import re
import sys
from pathlib import Path

RULES_PATH = Path(__file__).resolve().parent.parent / "rules" / "general.md"

BEGIN_MARKER = "  <!-- ai-slop:begin (generated by hooks/ai_slop.py) -->"
END_MARKER = "  <!-- ai-slop:end -->"


@dataclasses.dataclass(frozen=True)
class Entry:
    """One tic: how to catch it, what to call it, and how the rules file says it."""

    label: str
    bullet: str
    pattern: str | None = None
    hint: str = ""


# Order is the order the bullets appear in rules/general.md.
ENTRIES: tuple[Entry, ...] = (
    Entry(
        label="antithesis slop",
        bullet=(
            '- **Antithesis slop**: "It\'s not just X, it\'s Y", "It\'s X, not Y", "not only\n'
            '  X but Y". This is the worst offender. Never use it.'
        ),
        pattern=r"\b(?:it'?s|this is|that'?s|is|are)\s+not\s+(?:just|only|merely)\b"
        r"|\bnot only\b[^.\n]{0,80}\bbut(?:\s+also)?\b",
        hint='never "not just X, it\'s Y"; state the point directly',
    ),
    Entry(
        label="validation opener",
        bullet=(
            '- **Validation openers**: "Great question!", "You\'re absolutely right!",\n'
            '  "Good catch!". Just answer.'
        ),
        pattern=r"\bgreat question\b|\byou'?re absolutely right\b|\bgood catch\b",
        hint="just answer; drop the opener",
    ),
    Entry(
        label="self-narration",
        bullet=(
            '- **Self-narration**: "Let me help you with that", "I\'d be happy to", "As an\n'
            '  AI", "Based on my analysis". Do the work instead of announcing it.'
        ),
        pattern=r"\blet me help you\b|\bi'?d be happy to\b|\bas an ai\b|\bbased on my analysis\b",
        hint="do the work instead of announcing it",
    ),
    Entry(
        label="hedging padding",
        bullet=(
            '- **Hedging padding**: "I think", "it seems like", "it\'s worth noting that",\n'
            '  "in my opinion" as softeners on a claim I actually stand behind.'
        ),
        pattern=r"\bit'?s worth noting\b|\bit seems like\b|\bin my opinion\b",
        hint="state the claim directly or drop it",
    ),
    Entry(
        label="empty scaffolding",
        bullet=(
            '- **Empty scaffolding**: Restating the question before answering, "In\n'
            '  summary" or "To wrap up" on a short answer, trailing "Let me know if you\n'
            '  have any questions!" or "Feel free to...", headers and sections on\n'
            "  something that wants two sentences."
        ),
        pattern=r"\bin summary\b|\bto wrap up\b"
        r"|\blet me know if you have any questions\b|\bfeel free to\b",
        hint="end when the content is complete",
    ),
    Entry(
        label="inflated register",
        bullet=(
            '- **Inflated register**: "delve", "leverage", "utilize", "robust",\n'
            '  "seamless", "comprehensive", "crucial". Use plain words.'
        ),
        pattern=r"\bdelv(e|es|ed|ing)\b|\bleverag(e|es|ed|ing)\b|\butiliz(e|es|ed|ing)\b"
        r"|\brobust(ly|ness)?\b|\bseamless(ly)?\b|\bcomprehensive(ly)?\b|\bcrucial(ly)?\b",
        hint="use plain words (dig into, use, solid, smooth, complete, important)",
    ),
    Entry(
        label='inflated register, "load-bearing"',
        bullet=(
            '- **"Load-bearing"**: Say what the thing actually does: the choice the\n'
            "  value drives, the assumption the conclusion rests on, what breaks\n"
            "  without it."
        ),
        pattern=r"\bload[- ]bearing\b",
        hint=(
            "say what the thing does: the choice the value drives, the "
            "assumption the conclusion rests on, what breaks without it"
        ),
    ),
    Entry(
        label="rule-of-three reflex",
        bullet=(
            '- **Rule-of-three reflex**: "clear, concise, and correct". Do not pad to\n'
            "  three items or force symmetry where the content is not symmetric."
        ),
    ),
    Entry(
        label="fake balance",
        bullet=(
            '- **Fake balance**: "there are pros and cons to both" when one option is\n'
            "  obviously right. Commit to a recommendation instead of qualifying every\n"
            "  claim into mush."
        ),
        pattern=r"\bpros and cons\b",
        hint="commit to a recommendation",
    ),
    Entry(
        label="figurative verb slop",
        bullet=(
            '- **Figurative verb slop**: "stamps", "rides", "lands" and similar\n'
            '  metaphorical verbs for data movement ("the identifier rides the\n'
            '  metadata", "the event lands", "stamps the UUID"). Use literal verbs:\n'
            "  write, send, store, carry, arrive, complete. This applies everywhere,\n"
            "  including code comments, docstrings, identifiers, and test names."
        ),
        pattern=r"\bland(s|ed|ing)?\b|\brides?\b|\briding\b|\bstamp(s|ed|ing)?\b",
        hint="use a literal verb: write, send, store, carry, arrive, complete",
    ),
)

# Consumed by lint-outbound.py. Checked against inline-code-scrubbed prose
# outside fenced blocks, so identifiers like `landed_at` do not trip it.
AI_SLOP_PATTERNS: list[tuple[re.Pattern[str], str, str]] = [
    (re.compile(entry.pattern, re.I), entry.label, entry.hint)
    for entry in ENTRIES
    if entry.pattern is not None
]


def render_block() -> str:
    """The generated region of rules/general.md, markers included."""
    body = "\n".join(
        "\n".join(f"  {line}" if line else "" for line in entry.bullet.split("\n"))
        for entry in ENTRIES
    )
    return f"{BEGIN_MARKER}\n{body}\n{END_MARKER}"


def splice(text: str) -> str:
    """Replace the marked region of `text` with a freshly rendered block."""
    start = text.find(BEGIN_MARKER)
    end = text.find(END_MARKER)
    if start == -1 or end == -1:
        raise SystemExit(
            f"{RULES_PATH} has no ai-slop markers; add them around the "
            f'"do not speak like an LLM" bullets before syncing.'
        )
    return text[:start] + render_block() + text[end + len(END_MARKER) :]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--sync-rules", action="store_true", help="rewrite rules/general.md")
    group.add_argument("--check-rules", action="store_true", help="diff without writing")
    args = parser.parse_args()

    current = RULES_PATH.read_text()
    updated = splice(current)

    if args.sync_rules:
        if current == updated:
            print(f"{RULES_PATH.name} already current.")
            return 0
        RULES_PATH.write_text(updated)
        print(f"{RULES_PATH.name} updated from {len(ENTRIES)} entries.")
        return 0

    if current == updated:
        print(f"{RULES_PATH.name} matches ai_slop.py.")
        return 0
    sys.stdout.writelines(
        difflib.unified_diff(
            current.splitlines(keepends=True),
            updated.splitlines(keepends=True),
            fromfile=f"{RULES_PATH.name} (on disk)",
            tofile=f"{RULES_PATH.name} (from ai_slop.py)",
        )
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
