tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "coreutils"
brew "fzf"
brew "gnu-sed"
brew "go"
brew "httpie"
brew "hugo"
brew "jenv"
brew "jq"
brew "mas"
brew "mpv"
brew "nginx"
brew "nmap"
brew "node"
brew "nvm"
brew "pyenv"
brew "pyenv-virtualenvwrapper"
brew "python2"
brew "python3"
brew "rbenv"
brew "readline"
brew "terraform"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "vim"
brew "youtube-dl"

# mas "Bear", id: 1091189122
# mas "Gifox", id: 1082624744
# mas "Trello", id: 1278508951
