#!/usr/bin/bash
#
# USAGE
#
#   install
#
# DESCRIPTION
#
#   Creates symbolic links to configuration files found in a 'dotfiles'
#   directory.
#
# vim: fdm=marker

# Determine location of 'dotfiles' directory
DOTFILES=$(find "${HOME}" -type d -name "*dotfiles*")

echo "'dotfiles' was found at the following location: ${DOTFILES}"
read -rp "Do you wish to proceed? [Y/n]: " proceed

if [[ ! "${proceed}" =~ [Y|y|YES|yes] ]]; then
  echo 'Aborting...'
  exit
fi


# ${HOME}                                                                  {{{1
# -----------------------------------------------------------------------------

rm "${HOME}/.agignore"
ln -s "${DOTFILES}/.agignore" "${HOME}/.agignore"

rm "${HOME}/.cobra.yaml"
ln -s "${DOTFILES}/.cobra.yaml" "${HOME}/.cobra.yaml"

rm "${HOME}/.gitconfig"
ln -s "${DOTFILES}/.gitconfig" "${HOME}/.gitconfig"

rm "${HOME}/.gitignore"
ln -s "${DOTFILES}/.gitignore" "${HOME}/.gitignore"

rm "${HOME}/.powerline.conf"
ln -s "${DOTFILES}/.powerline.conf" "${HOME}/.powerline.conf"

rm "${HOME}/.tmux.conf"
ln -s "${DOTFILES}/.tmux.conf" "${HOME}/.tmux.conf"

rm "${HOME}/.vimrc"
ln -s "${DOTFILES}/.vimrc" "${HOME}/.vimrc"

rm "${HOME}/.zshrc"
ln -s "${DOTFILES}/.zshrc" "${HOME}/.zshrc"


# ${HOME}/.config                                                          {{{1
# -----------------------------------------------------------------------------

rm -rf "${HOME}/.config/mpv"
mkdir -p "${HOME}/.config/mpv"
ln -s "${DOTFILES}/.mpv/mpv.conf" "${HOME}/.config/mpv/mvp.conf"

rm -rf "${HOME}/.config/powerline"
mkdir -p "${HOME}/.config/powerline"
mkdir -p "${HOME}/.config/powerline/colorschemes/tmux"
mkdir -p "${HOME}/.config/powerline/themes/tmux"

ln -s "${DOTFILES}/.powerline/colorschemes/tmux/default.json" \
  "${HOME}/.config/powerline/colorschemes/tmux/default.json"
ln -s "${DOTFILES}/.powerline/colorschemes/tmux/solarized.json" \
  "${HOME}/.config/powerline/colorschemes/tmux/solarized.json"
ln -s "${DOTFILES}/.powerline/colorschemes/tmux/gruvbox.json" \
  "${HOME}/.config/powerline/colorschemes/tmux/gruvbox.json"

ln -s "${DOTFILES}/.powerline/colorschemes/default.json" \
  "${HOME}/.config/powerline/colorschemes/default.json"
ln -s "${DOTFILES}/.powerline/colorschemes/solarized.json" \
  "${HOME}/.config/powerline/colorschemes/solarized.json"
ln -s "${DOTFILES}/.powerline/colorschemes/gruvbox.json" \
  "${HOME}/.config/powerline/colorschemes/gruvbox.json"

ln -s "${DOTFILES}/.powerline/themes/tmux/default.json" \
  "${HOME}/.config/powerline/themes/tmux/default.json"
ln -s "${DOTFILES}/.powerline/themes/powerline_terminus.json" \
  "${HOME}/.config/powerline/themes/powerline_terminus.json"

ln -s "${DOTFILES}/.powerline/colors.json" \
  "${HOME}/.config/powerline/colors.json"
ln -s "${DOTFILES}/.powerline/config.json" \
  "${HOME}/.config/powerline/config.json"


# ${HOME}/.k9s                                                             {{{1
# -----------------------------------------------------------------------------

rm -rf "${HOME}/.k9s"
mkdir -p "${HOME}/.k9s"
ln -s "${DOTFILES}/.k9s/config.yml" "${HOME}/.k9s/config.yml"
ln -s "${DOTFILES}/.k9s/skin.yml" "${HOME}/.k9s/skin.yml"


# ${HOME}/.ssh                                                             {{{1
# -----------------------------------------------------------------------------

rm "${HOME}/.ssh/config"
ln -s "${DOTFILES}/.ssh/config" "${HOME}/.ssh/config"


# ${HOME}/.vim                                                             {{{1
# -----------------------------------------------------------------------------

rm "${HOME}/.vim/.en.utf-8.add"
ln -s "${DOTFILES}/.en.utf-8.add" "${HOME}/.vim/.en.utf-8.add"
