###############################################################################
# GitHub CLI Configuration
#
# DESCRIPTION
#   Configuration file for the GitHub CLI.
#
#   The GitHub CLI (gh) is a command-line tool for interacting with GitHub. It
#   lets you manage issues, PRs, repos, releases, workflows, and authentication
#   from the terminal.
#
#   See: https://cli.github.com
#
# INSTALLATION
#   Symlink file to $XDG_CONFIG_HOME/gh/hosts.yml
#
#     ln -s .config/gh/hosts.yml ${XDG_CONFIG_HOME}/gh/hosts.yml
###############################################################################

github.com:
  git_protocol: ssh
  users:
    nickolashkraus:
  user: nickolashkraus
